%% Search for a specified operating point for the model - F550_model_trim_ver2023b.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 24.1 and Simulink Control Design (TM) 24.1.
%
% Generated on: 12-Dec-2024 20:13:39

%% Specify the model name
model = 'F550_model_trim_ver2023b';

%% Create the operating point specification object.
opspec = operspec(model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, Max = Inf, dxMin = -Inf, and dxMax = Inf.

% State (1) - F550_model_trim_ver2023b/Subsystem Reference1/F550_Dynamic_Model/6DOF (Quaternion)/Calculate DCM & Euler Angles/q0 q1 q2 q3
% - Default model initial conditions are used to initialize optimization.

% State (2) - F550_model_trim_ver2023b/Subsystem Reference1/F550_Dynamic_Model/6DOF (Quaternion)/p,q,r
% - Default model initial conditions are used to initialize optimization.

% State (3) - F550_model_trim_ver2023b/Subsystem Reference1/F550_Dynamic_Model/6DOF (Quaternion)/ub,vb,wb
% - Default model initial conditions are used to initialize optimization.

% State (4) - F550_model_trim_ver2023b/Subsystem Reference1/F550_Dynamic_Model/6DOF (Quaternion)/xe,ye,ze
% - Default model initial conditions are used to initialize optimization.

% State (5) - F550_model_trim_ver2023b/Subsystem Reference1/F550_Dynamic_Model/Motor Model/MotorNonlinearDynamic1/Motor_Dynamics (1st order)/Integrator
% - Default model initial conditions are used to initialize optimization.

% State (6) - F550_model_trim_ver2023b/Subsystem Reference1/F550_Dynamic_Model/Motor Model/MotorNonlinearDynamic2/Motor_Dynamics (1st order)/Integrator
% - Default model initial conditions are used to initialize optimization.

% State (7) - F550_model_trim_ver2023b/Subsystem Reference1/F550_Dynamic_Model/Motor Model/MotorNonlinearDynamic3/Motor_Dynamics (1st order)/Integrator
% - Default model initial conditions are used to initialize optimization.

% State (8) - F550_model_trim_ver2023b/Subsystem Reference1/F550_Dynamic_Model/Motor Model/MotorNonlinearDynamic4/Motor_Dynamics (1st order)/Integrator
% - Default model initial conditions are used to initialize optimization.

% State (9) - F550_model_trim_ver2023b/Subsystem Reference1/F550_Dynamic_Model/Motor Model/MotorNonlinearDynamic5/Motor_Dynamics (1st order)/Integrator
% - Default model initial conditions are used to initialize optimization.

% State (10) - F550_model_trim_ver2023b/Subsystem Reference1/F550_Dynamic_Model/Motor Model/MotorNonlinearDynamic6/Motor_Dynamics (1st order)/Integrator
% - Default model initial conditions are used to initialize optimization.

%% Set the constraints on the inputs in the model.
% - The defaults for all inputs are Known = false, Min = -Inf, and
% Max = Inf.

% Input (1) - F550_model_trim_ver2023b/Control_Inputs
% - Default model initial conditions are used to initialize optimization.

%% Set the constraints on the outputs in the model.
% - The defaults for all outputs are Known = false, Min = -Inf, and
% Max = Inf.

% Output (1) - F550_model_trim_ver2023b/y
% - Default model initial conditions are used to initialize optimization.

% Output (2) - F550_model_trim_ver2023b/Vt
% - Default model initial conditions are used to initialize optimization.


%% Create the options
opt = findopOptions('DisplayReport','iter');

%% Perform the operating point search.
[op,opreport] = findop(model,opspec,opt);
